#!/bin/bash
pgrep -x sxhkd > /dev/null
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP2 -d 6 7 8


bspc config border_width         10
bspc config window_gap           4
bspc config top_padding			 18
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a mpv state=floating sticky=on
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled

~/.config/polybar/launch.sh
#~/.config/dzen/dzenbar/launch.sh
~/.config/scripts/bg.sh
sxhkd &
#Replace Capslock with Esc
#setxkbmap -option caps:backspace

#colors
#bspc config active_border_color "#f2aa83"
#bspc config focused_border_color "#F10490"
#bspc config focused_border_color "#2cfb7b"
#bspc config focused_border_color "#414141"
bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#282828"
xsetroot -cursor_name left_ptr
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
