require 'derp.ui.tree'
require 'derp.ui.git'
require 'derp.ui.lualine'
require 'derp.ui.components'
require 'derp.ui.terminal'
require 'derp.ui.barbar'
require 'derp.ui.dashboard'
require 'derp.ui.telescope'
