#!/bin/bash
pgrep -x sxhkd > /dev/null
bspc monitor eDP-1 -d 1 2 3 4 5

bspc monitor HDMI-2 -d 6 7 8


bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a mpv state=floating sticky=on
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled

~/.config/polybar/launch.sh
nitrogen --restore &
xinput set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" -0.75
xinput set-prop 14 306 1
xinput set-prop 9 315 -0.75
xinput set-prop 11 315 -0.75
pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
nm-applet &
sxhkd &

#Replace Capslock with Esc
setxkbmap -option caps:backspace

#colors
bspc config active_border_color "#f2aa83"
